# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LowInventoryAlarmSettingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lowInventoryAlarmSettingsWidget(object):
    def setupUi(self, lowInventoryAlarmSettingsWidget):
        lowInventoryAlarmSettingsWidget.setObjectName("lowInventoryAlarmSettingsWidget")
        lowInventoryAlarmSettingsWidget.resize(390, 207)
        self.groupBox = QtWidgets.QGroupBox(lowInventoryAlarmSettingsWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 141))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 30, 231, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lowInventorySetInput = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.lowInventorySetInput.setObjectName("lowInventorySetInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lowInventorySetInput)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setToolTip("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(lowInventoryAlarmSettingsWidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 160, 75, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(lowInventoryAlarmSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(lowInventoryAlarmSettingsWidget)

    def retranslateUi(self, lowInventoryAlarmSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        lowInventoryAlarmSettingsWidget.setWindowTitle(_translate("lowInventoryAlarmSettingsWidget", "Low Inventory Alarm Settings"))
        self.groupBox.setTitle(_translate("lowInventoryAlarmSettingsWidget", "Settings"))
        self.label.setText(_translate("lowInventoryAlarmSettingsWidget", "New threshold: "))
        self.label_2.setText(_translate("lowInventoryAlarmSettingsWidget", "Current threshold:"))
        self.lineEdit.setPlaceholderText(_translate("lowInventoryAlarmSettingsWidget", "8"))
        self.pushButton.setText(_translate("lowInventoryAlarmSettingsWidget", "Save"))
