""" # Form implementation generated from reading ui file 'CreateWorkOrderWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateWorkOrderWidget(object):
    def setupUi(self, CreateWorkOrderWidget):
        CreateWorkOrderWidget.setObjectName("CreateWorkOrderWidget")
        CreateWorkOrderWidget.resize(504, 484)
        self.createNewWOSaveButton = QtWidgets.QPushButton(parent=CreateWorkOrderWidget)
        self.createNewWOSaveButton.setGeometry(QtCore.QRect(340, 440, 141, 24))
        self.createNewWOSaveButton.setObjectName("createNewWOSaveButton")
        self.groupBox = QtWidgets.QGroupBox(parent=CreateWorkOrderWidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 310, 231, 161))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 212, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createWODeliveryAoFRadioButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.createWODeliveryAoFRadioButton.setObjectName("createWODeliveryAoFRadioButton")
        self.verticalLayout.addWidget(self.createWODeliveryAoFRadioButton)
        self.createWODeliveryOtherRadioButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.createWODeliveryOtherRadioButton.setObjectName("createWODeliveryOtherRadioButton")
        self.verticalLayout.addWidget(self.createWODeliveryOtherRadioButton)
        self.createWODeliveryPickupRadioButton = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.createWODeliveryPickupRadioButton.setObjectName("createWODeliveryPickupRadioButton")
        self.verticalLayout.addWidget(self.createWODeliveryPickupRadioButton)
        self.createNewWOBox = QtWidgets.QGroupBox(parent=CreateWorkOrderWidget)
        self.createNewWOBox.setGeometry(QtCore.QRect(10, 10, 481, 281))
        self.createNewWOBox.setObjectName("createNewWOBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.createNewWOBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 461, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.CreateWorkOrderNumberField = QtWidgets.QTextBrowser(parent=self.formLayoutWidget_2)
        self.CreateWorkOrderNumberField.setMaximumSize(QtCore.QSize(1000, 25))
        self.CreateWorkOrderNumberField.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.CreateWorkOrderNumberField.setObjectName("CreateWorkOrderNumberField")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.CreateWorkOrderNumberField)
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.createWOCustomerSelection = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.createWOCustomerSelection.setObjectName("createWOCustomerSelection")
        self.createWOCustomerSelection.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createWOCustomerSelection)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.createWODateInput = QtWidgets.QDateEdit(parent=self.formLayoutWidget_2)
        self.createWODateInput.setObjectName("createWODateInput")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createWODateInput)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.createWOQuantityInput = QtWidgets.QSpinBox(parent=self.formLayoutWidget_2)
        self.createWOQuantityInput.setObjectName("createWOQuantityInput")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createWOQuantityInput)
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.createWOProductionDateInput = QtWidgets.QDateEdit(parent=self.formLayoutWidget_2)
        self.createWOProductionDateInput.setObjectName("createWOProductionDateInput")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createWOProductionDateInput)
        self.requiredByDateLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.requiredByDateLabel.setObjectName("requiredByDateLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.requiredByDateLabel)
        self.createWORequiredByDate = QtWidgets.QDateEdit(parent=self.formLayoutWidget_2)
        self.createWORequiredByDate.setObjectName("createWORequiredByDate")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.createWORequiredByDate)
        self.productTemplateViewButton = QtWidgets.QPushButton(parent=CreateWorkOrderWidget)
        self.productTemplateViewButton.setGeometry(QtCore.QRect(340, 400, 141, 24))
        self.productTemplateViewButton.setObjectName("productTemplateViewButton")
        self.checkBox = QtWidgets.QCheckBox(CreateWorkOrderWidget)
        self.checkBox.setGeometry(QtCore.QRect(310, 360, 170, 30))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setText("Product Template Completed")

        self.retranslateUi(CreateWorkOrderWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateWorkOrderWidget)

    def retranslateUi(self, CreateWorkOrderWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateWorkOrderWidget.setWindowTitle(_translate("CreateWorkOrderWidget", "Create Work Order"))
        self.createNewWOSaveButton.setText(_translate("CreateWorkOrderWidget", "Save Work Order"))
        self.groupBox.setTitle(_translate("CreateWorkOrderWidget", "Shipping Method"))
        self.createWODeliveryAoFRadioButton.setText(_translate("CreateWorkOrderWidget", "Delivery (Address on File)"))
        self.createWODeliveryOtherRadioButton.setText(_translate("CreateWorkOrderWidget", "Delivery (Other)"))
        self.createWODeliveryPickupRadioButton.setText(_translate("CreateWorkOrderWidget", "Customer Pickup"))
        self.createNewWOBox.setTitle(_translate("CreateWorkOrderWidget", "Create New Work Order"))
        self.label_6.setText(_translate("CreateWorkOrderWidget", "Work Order Number"))
        self.CreateWorkOrderNumberField.setHtml(_translate("CreateWorkOrderWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#888888;\">Auto-generated upon completion</span></p></body></html>"))
        self.label.setText(_translate("CreateWorkOrderWidget", "Customer"))
        self.createWOCustomerSelection.setItemText(0, _translate("CreateWorkOrderWidget", "Select..."))
        self.label_2.setText(_translate("CreateWorkOrderWidget", "Order Date"))
        self.label_5.setText(_translate("CreateWorkOrderWidget", "Quantity"))
        self.label_7.setText(_translate("CreateWorkOrderWidget", "Production Date"))
        self.requiredByDateLabel.setText(_translate("CreateWorkOrderWidget", "Required By: "))
        self.productTemplateViewButton.setText(_translate("CreateWorkOrderWidget", "Product Template"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateWorkOrderWidget = QtWidgets.QWidget()
    ui = Ui_CreateWorkOrderWidget()
    ui.setupUi(CreateWorkOrderWidget)
    CreateWorkOrderWidget.show()
    sys.exit(app.exec())
 """