# Form implementation generated from reading ui file 'DeleteInventoryWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteInventoryWidget(object):
    def setupUi(self, DeleteInventoryWidget):
        DeleteInventoryWidget.setObjectName("DeleteInventoryWidget")
        DeleteInventoryWidget.resize(476, 404)
        self.deleteInventoryButton = QtWidgets.QPushButton(parent=DeleteInventoryWidget)
        self.deleteInventoryButton.setGeometry(QtCore.QRect(180, 350, 93, 28))
        self.deleteInventoryButton.setObjectName("deleteInventoryButton")
        self.recieveInventoryNoteBox = QtWidgets.QGroupBox(parent=DeleteInventoryWidget)
        self.recieveInventoryNoteBox.setGeometry(QtCore.QRect(10, 260, 441, 80))
        self.recieveInventoryNoteBox.setObjectName("recieveInventoryNoteBox")
        self.label_7 = QtWidgets.QLabel(parent=self.recieveInventoryNoteBox)
        self.label_7.setGeometry(QtCore.QRect(-10, 10, 381, 21))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(parent=DeleteInventoryWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 441, 231))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 411, 182))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.deleteInvItemID = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.deleteInvItemID.setObjectName("deleteInvItemID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deleteInvItemID)
        self.label_11 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.deleteInvInternalPartID = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.deleteInvInternalPartID.setObjectName("deleteInvInternalPartID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deleteInvInternalPartID)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.deleteInvItemName = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.deleteInvItemName.setObjectName("deleteInvItemName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deleteInvItemName)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.rdeleteInvDescription = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.rdeleteInvDescription.setObjectName("rdeleteInvDescription")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rdeleteInvDescription)
        self.deleteInvCost = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.deleteInvCost.setObjectName("deleteInvCost")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deleteInvCost)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.recieveInvQty_2 = QtWidgets.QSpinBox(parent=self.formLayoutWidget)
        self.recieveInvQty_2.setObjectName("recieveInvQty_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.recieveInvQty_2)
        self.label_8 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)

        self.retranslateUi(DeleteInventoryWidget)
        QtCore.QMetaObject.connectSlotsByName(DeleteInventoryWidget)

    def retranslateUi(self, DeleteInventoryWidget):
        _translate = QtCore.QCoreApplication.translate
        DeleteInventoryWidget.setWindowTitle(_translate("DeleteInventoryWidget", "Delete Inventory"))
        self.deleteInventoryButton.setText(_translate("DeleteInventoryWidget", "Delete"))
        self.recieveInventoryNoteBox.setTitle(_translate("DeleteInventoryWidget", "Notes:"))
        self.label_7.setText(_translate("DeleteInventoryWidget", "      This action cannot be undone"))
        self.groupBox.setTitle(_translate("DeleteInventoryWidget", "Delete Inventory Item"))
        self.label_2.setText(_translate("DeleteInventoryWidget", "Item ID"))
        self.label_11.setText(_translate("DeleteInventoryWidget", "Internal Part ID"))
        self.deleteInvInternalPartID.setPlaceholderText(_translate("DeleteInventoryWidget", "Internal Part ID"))
        self.label_3.setText(_translate("DeleteInventoryWidget", "Item Name"))
        self.label_5.setText(_translate("DeleteInventoryWidget", "Item Description"))
        self.rdeleteInvDescription.setPlaceholderText(_translate("DeleteInventoryWidget", "Auto-filled from Item ID"))
        self.deleteInvCost.setPlaceholderText(_translate("DeleteInventoryWidget", "Auto-filled from Item ID"))
        self.label_6.setText(_translate("DeleteInventoryWidget", "Item Cost"))
        self.label_8.setText(_translate("DeleteInventoryWidget", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteInventoryWidget = QtWidgets.QWidget()
    ui = Ui_DeleteInventoryWidget()
    ui.setupUi(DeleteInventoryWidget)
    DeleteInventoryWidget.show()
    sys.exit(app.exec())
