# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditUserWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editUserWidget(object):
    def setupUi(self, editUserWidget):
        editUserWidget.setObjectName("editUserWidget")
        editUserWidget.resize(341, 170)
        self.newUserGroupBox = QtWidgets.QGroupBox(editUserWidget)
        self.newUserGroupBox.setGeometry(QtCore.QRect(20, 10, 300, 151))
        self.newUserGroupBox.setObjectName("newUserGroupBox")
        self.saveChangesButton = QtWidgets.QPushButton(self.newUserGroupBox)
        self.saveChangesButton.setGeometry(QtCore.QRect(90, 120, 101, 24))
        self.saveChangesButton.setObjectName("saveChangesButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.newUserGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.editUserEmployeeNumber = QtWidgets.QComboBox(self.formLayoutWidget)
        self.editUserEmployeeNumber.setObjectName("editUserEmployeeNumber")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editUserEmployeeNumber)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.editUserRights = QtWidgets.QComboBox(self.formLayoutWidget)
        self.editUserRights.setObjectName("editUserRights")
        self.editUserRights.addItem("")
        self.editUserRights.addItem("")
        self.editUserRights.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editUserRights)
        self.editUserUsername = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.editUserUsername.setObjectName("editUserUsername")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editUserUsername)

        self.retranslateUi(editUserWidget)
        QtCore.QMetaObject.connectSlotsByName(editUserWidget)

    def retranslateUi(self, editUserWidget):
        _translate = QtCore.QCoreApplication.translate
        editUserWidget.setWindowTitle(_translate("editUserWidget", "Edit User"))
        self.newUserGroupBox.setTitle(_translate("editUserWidget", "Edit User"))
        self.saveChangesButton.setText(_translate("editUserWidget", "Save Changes"))
        self.label_12.setText(_translate("editUserWidget", "Employee Number"))
        self.label.setText(_translate("editUserWidget", "Username"))
        self.label_17.setText(_translate("editUserWidget", "Rights"))
        self.editUserRights.setItemText(0, _translate("editUserWidget", "---"))
        self.editUserRights.setItemText(1, _translate("editUserWidget", "Admin"))
        self.editUserRights.setItemText(2, _translate("editUserWidget", "User"))
        self.editUserUsername.setPlaceholderText(_translate("editUserWidget", "Auto-fill from User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editUserWidget = QtWidgets.QWidget()
    ui = Ui_editUserWidget()
    ui.setupUi(editUserWidget)
    editUserWidget.show()
    sys.exit(app.exec_())
