# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditOperatorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editOperatorWidget(object):
    def setupUi(self, editOperatorWidget):
        editOperatorWidget.setObjectName("editOperatorWidget")
        editOperatorWidget.resize(438, 168)
        self.groupBox = QtWidgets.QGroupBox(editOperatorWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 101))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 74))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.editEmployeeNumberInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.editEmployeeNumberInput.setObjectName("editEmployeeNumberInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editEmployeeNumberInput)
        self.editOperatorNameInput = QtWidgets.QComboBox(self.formLayoutWidget)
        self.editOperatorNameInput.setObjectName("editOperatorNameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editOperatorNameInput)
        self.saveOperatorButton = QtWidgets.QPushButton(editOperatorWidget)
        self.saveOperatorButton.setGeometry(QtCore.QRect(130, 120, 131, 24))
        self.saveOperatorButton.setObjectName("saveOperatorButton")

        self.retranslateUi(editOperatorWidget)
        QtCore.QMetaObject.connectSlotsByName(editOperatorWidget)

    def retranslateUi(self, editOperatorWidget):
        _translate = QtCore.QCoreApplication.translate
        editOperatorWidget.setWindowTitle(_translate("editOperatorWidget", "Edit Operator"))
        self.groupBox.setTitle(_translate("editOperatorWidget", "Edit Operator"))
        self.label.setText(_translate("editOperatorWidget", "Operator Name"))
        self.label_2.setText(_translate("editOperatorWidget", "Employee Number"))
        self.saveOperatorButton.setText(_translate("editOperatorWidget", "Save Changes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editOperatorWidget = QtWidgets.QWidget()
    ui = Ui_editOperatorWidget()
    ui.setupUi(editOperatorWidget)
    editOperatorWidget.show()
    sys.exit(app.exec_())
