# Form implementation generated from reading ui file 'EditPasswordWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditUserWidget(object):
    def setupUi(self, EditUserWidget):
        EditUserWidget.setObjectName("EditUserWidget")
        EditUserWidget.resize(313, 169)
        self.editUserGroupBox = QtWidgets.QGroupBox(parent=EditUserWidget)
        self.editUserGroupBox.setGeometry(QtCore.QRect(10, 10, 300, 150))
        self.editUserGroupBox.setObjectName("editUserGroupBox")
        self.saveUserChangesButton = QtWidgets.QPushButton(parent=self.editUserGroupBox)
        self.saveUserChangesButton.setGeometry(QtCore.QRect(70, 110, 131, 24))
        self.saveUserChangesButton.setObjectName("saveUserChangesButton")
        self.formLayoutWidget_5 = QtWidgets.QWidget(parent=self.editUserGroupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 261, 91))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_15 = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        self.label_15.setObjectName("label_15")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_15)
        self.comboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget_5)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox)
        self.label_13 = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.editUserUsername = QtWidgets.QLineEdit(parent=self.formLayoutWidget_5)
        self.editUserUsername.setObjectName("editUserUsername")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editUserUsername)
        self.label_16 = QtWidgets.QLabel(parent=self.formLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_16)
        self.editUserRights = QtWidgets.QComboBox(parent=self.formLayoutWidget_5)
        self.editUserRights.setObjectName("editUserRights")
        self.editUserRights.addItem("")
        self.editUserRights.addItem("")
        self.editUserRights.addItem("")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editUserRights)

        self.retranslateUi(EditUserWidget)
        QtCore.QMetaObject.connectSlotsByName(EditUserWidget)

    def retranslateUi(self, EditUserWidget):
        _translate = QtCore.QCoreApplication.translate
        EditUserWidget.setWindowTitle(_translate("EditUserWidget", "Edit User"))
        self.editUserGroupBox.setTitle(_translate("EditUserWidget", "Edit User"))
        self.saveUserChangesButton.setText(_translate("EditUserWidget", "Save Changes"))
        self.label_15.setText(_translate("EditUserWidget", "Employee Number"))
        self.label_13.setText(_translate("EditUserWidget", "Username"))
        self.editUserUsername.setPlaceholderText(_translate("EditUserWidget", "Auto-fills from Employee Number"))
        self.label_16.setText(_translate("EditUserWidget", "Rights"))
        self.editUserRights.setItemText(0, _translate("EditUserWidget", "---"))
        self.editUserRights.setItemText(1, _translate("EditUserWidget", "Admin"))
        self.editUserRights.setItemText(2, _translate("EditUserWidget", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditUserWidget = QtWidgets.QWidget()
    ui = Ui_EditUserWidget()
    ui.setupUi(EditUserWidget)
    EditUserWidget.show()
    sys.exit(app.exec())
