# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MachineList.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MachineList(object):
    def setupUi(self, MachineList):
        MachineList.setObjectName("MachineList")
        MachineList.resize(450, 289)
        self.groupBox = QtWidgets.QGroupBox(MachineList)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 391, 241))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 351, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)

        self.retranslateUi(MachineList)
        QtCore.QMetaObject.connectSlotsByName(MachineList)

    def retranslateUi(self, MachineList):
        _translate = QtCore.QCoreApplication.translate
        MachineList.setWindowTitle(_translate("MachineList", "Machine List"))
        self.groupBox.setTitle(_translate("MachineList", "Machine List"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MachineList", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MachineList", "Machine"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MachineList", "Time Estimate Per Product"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MachineList", "Drilling"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MachineList", "12 seconds"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MachineList = QtWidgets.QWidget()
    ui = Ui_MachineList()
    ui.setupUi(MachineList)
    MachineList.show()
    sys.exit(app.exec_())
