# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProductionSystemsManagerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_productionSystemsManagerWidget(object):
    def setupUi(self, productionSystemsManagerWidget):
        productionSystemsManagerWidget.setObjectName("productionSystemsManagerWidget")
        productionSystemsManagerWidget.resize(859, 488)
        self.FactoryImg = QtWidgets.QLabel(productionSystemsManagerWidget)
        self.FactoryImg.setGeometry(QtCore.QRect(370, 20, 471, 411))
        self.FactoryImg.setText("")
        self.FactoryImg.setPixmap(QtGui.QPixmap(r"src\frontend\PyGUIs\FestoCompleteSystem408highres.png"))
        self.FactoryImg.setScaledContents(True)
        self.FactoryImg.setWordWrap(True)
        self.FactoryImg.setObjectName("FactoryImg")
        self.groupBox_2 = QtWidgets.QGroupBox(productionSystemsManagerWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 341, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 331, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.executeProductionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.executeProductionButton.setObjectName("executeProductionButton")
        self.verticalLayout.addWidget(self.executeProductionButton)
        self.kPIButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.kPIButton.setObjectName("kPIButton")
        self.verticalLayout.addWidget(self.kPIButton)
        self.operatorManagerButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.operatorManagerButton.setObjectName("operatorManagerButton")
        self.verticalLayout.addWidget(self.operatorManagerButton)
        self.label = QtWidgets.QLabel(productionSystemsManagerWidget)
        self.label.setGeometry(QtCore.QRect(30, 180, 271, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"src\frontend\PyGUIs\DrillingModule.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(productionSystemsManagerWidget)
        QtCore.QMetaObject.connectSlotsByName(productionSystemsManagerWidget)

    def retranslateUi(self, productionSystemsManagerWidget):
        _translate = QtCore.QCoreApplication.translate
        productionSystemsManagerWidget.setWindowTitle(_translate("productionSystemsManagerWidget", "Production Systems Manager"))
        self.FactoryImg.setToolTip(_translate("productionSystemsManagerWidget", "Photo Courtesy of Festo"))
        self.groupBox_2.setTitle(_translate("productionSystemsManagerWidget", "Factory"))
        self.executeProductionButton.setToolTip(_translate("productionSystemsManagerWidget", "Used to execute a production order immediately"))
        self.executeProductionButton.setText(_translate("productionSystemsManagerWidget", "Execute Production"))
        self.kPIButton.setText(_translate("productionSystemsManagerWidget", "Key Performance Indicators"))
        self.operatorManagerButton.setText(_translate("productionSystemsManagerWidget", "Operator Manager"))
        self.label.setToolTip(_translate("productionSystemsManagerWidget", "Photo Courtesy of Festo"))
