# Form implementation generated from reading ui file 'TaskCodeSelection.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 317)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 441, 251))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 381, 179))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.taskCodeSlider = QtWidgets.QSlider(parent=self.gridLayoutWidget)
        self.taskCodeSlider.setAcceptDrops(False)
        self.taskCodeSlider.setMinimum(0)
        self.taskCodeSlider.setMaximum(3)
        self.taskCodeSlider.setProperty("value", 0)
        self.taskCodeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.taskCodeSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.taskCodeSlider.setObjectName("taskCodeSlider")
        self.gridLayout.addWidget(self.taskCodeSlider, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Task Code Selection"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Task 0: Passthrough (no drilling).</p><p>Task 1: Drill back two holes. </p><p>Task 2: Drill front two holes.</p><p>Task 3: Drill all four holes (two front, two back). </p></body></html>"))
        self.label.setText(_translate("Form", "0                                        1                                       2                                       3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
