# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewScheduleWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 480)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 591, 401))
        self.groupBox.setObjectName("groupBox")
        self.allWorkOrderTable = QtWidgets.QTableWidget(self.groupBox)
        self.allWorkOrderTable.setGeometry(QtCore.QRect(30, 30, 531, 341))
        self.allWorkOrderTable.setObjectName("allWorkOrderTable")
        self.allWorkOrderTable.setColumnCount(4)
        self.allWorkOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allWorkOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allWorkOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allWorkOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allWorkOrderTable.setHorizontalHeaderItem(3, item)
        self.allWorkOrderTable.horizontalHeader().setDefaultSectionSize(125)
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.refreshButton.setObjectName("refreshButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Scheduled Work Orders"))
        item = self.allWorkOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Work Order No."))
        item = self.allWorkOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Scheduled Start Date"))
        item = self.allWorkOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Scheduled Start Time"))
        item = self.allWorkOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Estimated Time"))
        self.refreshButton.setText(_translate("Form", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
