# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutWidget(object):
    def setupUi(self, AboutWidget):
        AboutWidget.setObjectName("AboutWidget")
        AboutWidget.resize(357, 346)
        self.groupBox = QtWidgets.QGroupBox(AboutWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 311, 191))
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 281, 151))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtWidgets.QGroupBox(AboutWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 311, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(AboutWidget)
        QtCore.QMetaObject.connectSlotsByName(AboutWidget)

    def retranslateUi(self, AboutWidget):
        _translate = QtCore.QCoreApplication.translate
        AboutWidget.setWindowTitle(_translate("AboutWidget", "About"))
        self.groupBox.setTitle(_translate("AboutWidget", "About"))
        self.label_9.setText(_translate("AboutWidget", "This software designed as a partial fulfillment of the requirements outlined in the course syallbus of MANF-555: Factory Planning. It was designed and constructed over the W1 2024/25 Term at UBC Okanagan. All work was completed by the developers listed below."))
        self.groupBox_2.setTitle(_translate("AboutWidget", "Developers"))
        self.label.setText(_translate("AboutWidget", "James Ropotar"))
        self.label_2.setText(_translate("AboutWidget", "Jonathan Kettle"))
        self.label_3.setText(_translate("AboutWidget", "Morgan Davies"))
