# Form implementation generated from reading ui file 'CreateNewInventory.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createNewInventorWidget(object):
    def setupUi(self, createNewInventorWidget):
        createNewInventorWidget.setObjectName("createNewInventorWidget")
        createNewInventorWidget.resize(461, 404)
        self.newInventorySaveButton = QtWidgets.QPushButton(parent=createNewInventorWidget)
        self.newInventorySaveButton.setGeometry(QtCore.QRect(190, 340, 93, 28))
        self.newInventorySaveButton.setObjectName("newInventorySaveButton")
        self.groupBox = QtWidgets.QGroupBox(parent=createNewInventorWidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 421, 221))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 401, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.newInvItemName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.newInvItemName.setObjectName("newInvItemName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.newInvItemName)
        self.newInvItemDescription = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.newInvItemDescription.setObjectName("newInvItemDescription")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.newInvItemDescription)
        self.newInvItemCost = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.newInvItemCost.setObjectName("newInvItemCost")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.newInvItemCost)
        self.newInvItemQty = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.newInvItemQty.setObjectName("newInvItemQty")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.newInvItemQty)
        self.newInvInternalPartID = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.newInvInternalPartID.setObjectName("newInvInternalPartID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.newInvInternalPartID)
        self.label_11 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.createNewInventoryNoteBox = QtWidgets.QGroupBox(parent=createNewInventorWidget)
        self.createNewInventoryNoteBox.setGeometry(QtCore.QRect(30, 240, 421, 80))
        self.createNewInventoryNoteBox.setObjectName("createNewInventoryNoteBox")
        self.label_8 = QtWidgets.QLabel(parent=self.createNewInventoryNoteBox)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 381, 21))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(createNewInventorWidget)
        QtCore.QMetaObject.connectSlotsByName(createNewInventorWidget)

    def retranslateUi(self, createNewInventorWidget):
        _translate = QtCore.QCoreApplication.translate
        createNewInventorWidget.setWindowTitle(_translate("createNewInventorWidget", "Create New Inventory"))
        self.newInventorySaveButton.setText(_translate("createNewInventorWidget", "Save"))
        self.groupBox.setTitle(_translate("createNewInventorWidget", "Create New Inventory"))
        self.label.setText(_translate("createNewInventorWidget", "Item Name"))
        self.label_2.setText(_translate("createNewInventorWidget", "Item Description"))
        self.label_3.setText(_translate("createNewInventorWidget", "Qty On Hand"))
        self.label_4.setText(_translate("createNewInventorWidget", "Item Cost"))
        self.newInvItemName.setPlaceholderText(_translate("createNewInventorWidget", "Item Name"))
        self.newInvItemDescription.setPlaceholderText(_translate("createNewInventorWidget", "Item Description"))
        self.newInvItemCost.setPlaceholderText(_translate("createNewInventorWidget", "Item Cost"))
        self.newInvItemQty.setPlaceholderText(_translate("createNewInventorWidget", "Qty On Hand"))
        self.newInvInternalPartID.setPlaceholderText(_translate("createNewInventorWidget", "Internal Part ID"))
        self.label_11.setText(_translate("createNewInventorWidget", "Internal Part ID"))
        self.createNewInventoryNoteBox.setTitle(_translate("createNewInventorWidget", "Notes:"))
        self.label_8.setText(_translate("createNewInventorWidget", "Use this module while creating new inventory items."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createNewInventorWidget = QtWidgets.QWidget()
    ui = Ui_createNewInventorWidget()
    ui.setupUi(createNewInventorWidget)
    createNewInventorWidget.show()
    sys.exit(app.exec())
